# Generated by Django 4.1.4 on 2022-12-24 23:03

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='salead',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.websiteuser'),
        ),
    ]
