# Generated by Django 4.1.4 on 2022-12-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_rename_user_salead_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='salead',
            name='date_paid',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='salead',
            name='date_retired',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='salead',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salead',
            name='is_retired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salead',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
