# Generated by Django 4.1.4 on 2022-12-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_salead_date_paid_salead_date_retired_salead_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salead',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='salead',
            name='date_paid',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='salead',
            name='date_retired',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
