# Generated by Django 4.1.4 on 2022-12-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_salead_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salead',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salead',
            name='date_paid',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='salead',
            name='date_retired',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
