# Generated by Django 4.1.4 on 2022-12-29 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_salead_date_created_alter_salead_date_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salead',
            options={'ordering': ['-date_created']},
        ),
    ]
