# Generated by Django 4.1.4 on 2023-01-09 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_salead_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustration',
            name='salead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='ads.salead'),
        ),
        migrations.AlterField(
            model_name='salead',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleads', to='ads.websiteuser'),
        ),
    ]
